export enum ActionType {
    SINGLE_EMOTICON = 'SINGLE_EMOTICON',
    MULTI_EMOTICON = 'MULTI_EMOTICON',
    STEAL_GOKART = 'STEAL_GOKART',
    GET_PLAYERS = 'GET_PLAYERS',
}

export enum MessageSource {
    GATHER = 'GATHER',
    EXTENSION = 'EXTENSION',
}
